//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace McoEasyTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class AD_Settings
    {
        public bool DurationFilter { get; set; }
        public bool StateFilter { get; set; }
        public bool PingFilter { get; set; }
        public bool ErrorFilter { get; set; }
        public int Duration { get; set; }
        public string State { get; set; }
        public string Errors { get; set; }
        public int Id { get; set; }
        public string MemoryErrors { get; set; }
    }
}
