//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace McoEasyTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application
    {
        public Application()
        {
            this.Application_Reports = new HashSet<Application_Report>();
            this.AppHtmlElements = new HashSet<AppHtmlElement>();
            this.Scheduled_Applications = new HashSet<Scheduled_Application>();
            this.AppServers = new HashSet<AppServer>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public string Url { get; set; }
        public Nullable<int> Domain { get; set; }
        public string Navigator { get; set; }
    
        public virtual ICollection<Application_Report> Application_Reports { get; set; }
        public virtual ICollection<AppHtmlElement> AppHtmlElements { get; set; }
        public virtual ICollection<Scheduled_Application> Scheduled_Applications { get; set; }
        public virtual ICollection<AppServer> AppServers { get; set; }
    }
}
