//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace McoEasyTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class Application_Report
    {
        public Application_Report()
        {
            this.AppServer_Reports = new HashSet<AppServer_Report>();
        }
    
        public int Id { get; set; }
        public string State { get; set; }
        public string Details { get; set; }
        public string Linkable { get; set; }
        public string Authentified { get; set; }
        public int AppReportId { get; set; }
        public int ApplicationId { get; set; }
    
        public virtual AppReport AppReport { get; set; }
        public virtual Application Application { get; set; }
        public virtual ICollection<AppServer_Report> AppServer_Reports { get; set; }
    }
}
