//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace McoEasyTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppReport : Report
    {
        public AppReport()
        {
            this.Application_Reports = new HashSet<Application_Report>();
        }
    
    
        public virtual ICollection<Application_Report> Application_Reports { get; set; }
    }
}
