//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace McoEasyTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppSchedule : Schedule
    {
        public AppSchedule()
        {
            this.Scheduled_Applications = new HashSet<Scheduled_Application>();
        }
    
        public bool AutoRelaunch { get; set; }
    
        public virtual ICollection<Scheduled_Application> Scheduled_Applications { get; set; }
    }
}
