//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace McoEasyTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class AppServer_Report
    {
        public int Id { get; set; }
        public string Ping { get; set; }
        public string State { get; set; }
        public string Details { get; set; }
        public int Application_ReportId { get; set; }
        public int AppServerId { get; set; }
    
        public virtual AppServer AppServer { get; set; }
        public virtual Application_Report Application_Report { get; set; }
    }
}
