//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace McoEasyTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class BackupReport : Report
    {
        public BackupReport()
        {
            this.BackupServer_Reports = new HashSet<BackupServer_Report>();
        }
    
        public int WeekNumber { get; set; }
        public System.DateTime LastUpdate { get; set; }
    
        public virtual ICollection<BackupServer_Report> BackupServer_Reports { get; set; }
    }
}
