//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace McoEasyTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class BackupServer_Report
    {
        public int Id { get; set; }
        public string State { get; set; }
        public string Ping { get; set; }
        public string Services { get; set; }
        public string Relaunched { get; set; }
        public string Details { get; set; }
        public int BackupReportId { get; set; }
        public int BackupServerId { get; set; }
    
        public virtual BackupReport BackupReport { get; set; }
        public virtual BackupServer BackupServer { get; set; }
    }
}
