//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace McoEasyTool
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DataModelContainer : DbContext
    {
        public DataModelContainer()
            : base("name=DataModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<FaultyServer_Report> FaultyServerReports { get; set; }
        public virtual DbSet<Recipient> Recipients { get; set; }
        public virtual DbSet<ReftechServers> ReftechServers { get; set; }
        public virtual DbSet<Pool> Pools { get; set; }
        public virtual DbSet<BackupServer_Report> BackupServerReports { get; set; }
        public virtual DbSet<AD_Settings> AD_Settings { get; set; }
        public virtual DbSet<Application> Applications { get; set; }
        public virtual DbSet<Application_Report> ApplicationAppReports { get; set; }
        public virtual DbSet<AppServer_Report> AppServerAppReports { get; set; }
        public virtual DbSet<AppHtmlElement> AppHtmlElements { get; set; }
        public virtual DbSet<Scheduled_Application> ScheduledApplications { get; set; }
        public virtual DbSet<Email> Emails { get; set; }
        public virtual DbSet<Report> Reports { get; set; }
        public virtual DbSet<Schedule> Schedules { get; set; }
        public virtual DbSet<Server> Servers { get; set; }
        public virtual DbSet<AppDomain> AppDomains { get; set; }
        public virtual DbSet<SpaceServer_Report> SpaceServer_Reports { get; set; }
        public virtual DbSet<Account> Accounts { get; set; }

        //Active Directory
        public DbSet<FaultyServer> FaultyServers { get; set; }
        public DbSet<AdReport> AdReports { get; set; }
        public DbSet<AdSchedule> AdSchedules { get; set; }

        //End Active Directory

        //Backup Exec
        public DbSet<BackupServer> BackupServers { get; set; }
        public DbSet<BackupReport> BackupReports { get; set; }
        public DbSet<BackupSchedule> BackupSchedules { get; set; }
        //End Backup Exec

        //Application
        public DbSet<Application_Report> ApplicationReports { get; set; }
        public DbSet<AppServer_Report> AppServerReports { get; set; }
        public DbSet<AppServer> AppServers { get; set; }
        public DbSet<AppReport> AppReports { get; set; }
        public DbSet<AppSchedule> AppSchedules { get; set; }
        //End Application


        //Space Exec
        public DbSet<SpaceServer> SpaceServers { get; set; }
        public DbSet<SpaceServer_Report> SpaceServerReports { get; set; }
        public DbSet<SpaceReport> SpaceReports { get; set; }
        public DbSet<SpaceSchedule> SpaceSchedules { get; set; }
        //End Space Exec
    }
}
