//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace McoEasyTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class FaultyServer_Report
    {
        public int Id { get; set; }
        public string Ping { get; set; }
        public string Details { get; set; }
        public string AbsenceDuration { get; set; }
        public string Ticket { get; set; }
        public int AdReportId { get; set; }
        public int FaultyServerId { get; set; }
    
        public virtual AdReport AdReport { get; set; }
        public virtual FaultyServer FaultyServer { get; set; }
    }
}
