//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace McoEasyTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pool
    {
        public Pool()
        {
            this.BackupServers = new HashSet<BackupServer>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int BackupDay { get; set; }
        public int CheckDay { get; set; }
        public string CellColor { get; set; }
        public string CheckFolder { get; set; }
        public string BackupManager { get; set; }
        public string ExecutionAccount { get; set; }
        public string CheckAccount { get; set; }
    
        public virtual ICollection<BackupServer> BackupServers { get; set; }
    }
}
