//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace McoEasyTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class Recipient
    {
        public int Id { get; set; }
        public string RelativeAddress { get; set; }
        public string AbsoluteAddress { get; set; }
        public string Name { get; set; }
        public string Module { get; set; }
        public Nullable<bool> Included { get; set; }
    }
}
