//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace McoEasyTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule
    {
        public Schedule()
        {
            this.Reports = new HashSet<Report>();
        }
    
        public int Id { get; set; }
        public System.DateTime CreationTime { get; set; }
        public string Multiplicity { get; set; }
        public string TaskName { get; set; }
        public string Generator { get; set; }
        public Nullable<int> Executed { get; set; }
        public Nullable<System.DateTime> NextExecution { get; set; }
        public string State { get; set; }
        public string Module { get; set; }
    
        public virtual ICollection<Report> Reports { get; set; }
    }
}
