//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace McoEasyTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class Scheduled_Application
    {
        public int Id { get; set; }
        public int AppScheduleId { get; set; }
        public int ApplicationId { get; set; }
    
        public virtual AppSchedule AppSchedule { get; set; }
        public virtual Application Application { get; set; }
    }
}
