//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace McoEasyTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpaceServer : Server
    {
        public SpaceServer()
        {
            this.SpaceServer_Reports = new HashSet<SpaceServer_Report>();
        }
    
        public Nullable<bool> Included { get; set; }
        public string Disks { get; set; }
        public bool IsShare { get; set; }
        public string CellColor { get; set; }
        public string ExecutionAccount { get; set; }
        public string CheckAccount { get; set; }
    
        public virtual ICollection<SpaceServer_Report> SpaceServer_Reports { get; set; }
    }
}
