//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace McoEasyTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpaceReport : Report
    {
        public SpaceReport()
        {
            this.SpaceServer_Reports = new HashSet<SpaceServer_Report>();
        }
    
    
        public virtual ICollection<SpaceServer_Report> SpaceServer_Reports { get; set; }
    }
}
